type: object
required:
  - teamId
  - name
  - description
  - deadline
properties:
  id:
    type: integer
    description: The unique identifier for the task.
    example: 1
  teamId:
    type: integer
    description: The ID of the team this task belongs to.
    example: 2
  name:
    type: string
    description: The name of the project.
    example: Assignment 1
  description:
    type: string
    description: A description of the project.
    example: AI Linear Regression Assignment.
  deadline:
    type: string
    format: date-time
    description: The deadline for the project. Must be a valid date in the future.
    example: 2013-09-29T18:46:19Z
example:
  id: 1
  teamId: 2
  name: Design Homepage
  description: Create a responsive design for the homepage with the new branding guidelines.
  deadline: 2013-09-29T18:46:19Z
