openapi: "3.0.3"
info:
  title: poptask
  description: API documentation for the poptask application.
  version: "1.0"
servers:
  - url: https://localhost:3000/api/v1

# Reference paths and components
paths:
  $ref: "./paths/index.yaml"

components:
  $ref: "./components/index.yaml"

security:
  - BearerAuth: []
